=== Starlink/starjava/util/src/main/java/uk/ac/starlink/util/text/toc_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!-- 
    This is the DTD for TOC
    Copyright (c) 1998 Sun Microsystems

    @(#)toc_1_0.dtd 1.3 01/03/99
-->


<!-- A TOC.  It is versioned -->

<!ELEMENT toc (tocitem*)>
  <!ATTLIST toc version CDATA #FIXED "1.0">
  <!ATTLIST toc xml:lang CDATA #IMPLIED>

<!-- an item -->

<!ELEMENT tocitem (#PCDATA | tocitem)*>
  <!ATTLIST tocitem xml:lang CDATA #IMPLIED>
  <!ATTLIST tocitem text CDATA #IMPLIED>
  <!ATTLIST tocitem image CDATA #IMPLIED>
  <!ATTLIST tocitem target CDATA #IMPLIED>

<!-- 
  Change list:

  Created - epll, 16 Dec '98
 -->

=== Starlink/starjava/splat/src/docs/TOC.xml
<?xml version='1.0' encoding='ISO-8859-1' ?>
<!DOCTYPE toc
  PUBLIC "-//Sun Microsystems Inc.//DTD JavaHelp TOC Version 1.0//EN"
         "http://java.sun.com/products/javahelp/toc_1_0.dtd">

<toc version="1.0">
   <tocitem target="splat-help" text="SPLAT-VO help system"/>
   <tocitem target="abstract" text="Abstract"/>
   <tocitem target="introduction" text="Overview"/>
   <tocitem target="getting-started" text="Getting started"/>
   <tocitem target="displaying-a-spectrum" text="Displaying a spectrum"/>
   <tocitem target="displaying-many-spectra" text="Displaying many spectra"/>
   <tocitem target="plot-control" text="Basic plot control"/>
   <tocitem target="window-level-help" text="Individual window help"/>
   <tocitem target="browser-window" text="Browser window"/>
   <tocitem target="plot-window" text="Plot window"/>
   <tocitem target="ssa-window" text="Query VO for spectra"/>
       <tocitem target="ssa-metadata" text="Query VO for metadata"/>
   <tocitem target="animation-window" text="Animation window"/>
   <tocitem target="viewer" text="View/modify values window"/>
   <tocitem target="specxcoord-window" text="Coordinate system attributes window"/>
   <tocitem target="dataunits-window" text="Data units window"/>
   <tocitem target="binary-maths" text="Binary maths window" />
   <tocitem target="unary-maths" text="Constant maths window" />
   <tocitem target="panner-window" text="Panner window" />
   <tocitem target="config-window" text="Plot configuration window">
      <tocitem target="config-window-limits" text="Data Limits" />
      <tocitem target="config-window-title" text="Title" />
      <tocitem target="config-window-axis-labels" text="Axis labels"/>
      <tocitem target="config-window-axis-numbers" text="Axis numbers" />
      <tocitem target="config-window-axes" text="Axes" />
      <tocitem target="config-window-grid" text="Grid lines" />
      <tocitem target="config-window-border" text="Border lines" />
      <tocitem target="config-window-ticks" text="Ticks" />
      <tocitem target="config-window-render" text="Graphics rendering" />
      <tocitem target="config-window-edge" text="Edges" />
      <tocitem target="config-window-background" text="Background" />
   </tocitem>
   <tocitem target="cutter-window" text="Region extraction window" />
   <tocitem target="polynomial-fit-window" text="Fit polynomial to regions window" />
   <tocitem target="interpolation-window" text="Generate spectra from interpolated lines" />
   <tocitem target="line-fit-window" text="Measure spectral lines window">
      <tocitem target="line-fit-saving-window" text="Save spectral line measurements"/>
   </tocitem>        
   <tocitem target="filter-window" text="Filter spectrum window" />
   <tocitem target="simpleunits-window" text="Change units window" />
   <tocitem target="flipper-window" text="Flip, shift or redshift window" />
   <tocitem target="stats-window" text="Region statistics window" />
   <tocitem target="stacker-window" text="Display stacked spectra window" />
   <tocitem target="data-formats" text="Supported data formats"/>
   <tocitem target="command-line" text="Command-line utilities" />
   <tocitem target="interop" text="Interoperability">
       <tocitem target="samp" text="SAMP"/>
       <tocitem target="plastic" text="PLASTIC"/>
   </tocitem>
   <tocitem target="acknowledgements" text="Acknowledgements"/>

</toc>
