=== Starlink/starjava/util/src/main/java/uk/ac/starlink/util/text/VOTable.dtd
<!-- VOTABLE is the root element 
.Version 1.1 Addition of GROUP utype
-->
<!ELEMENT VOTABLE (DESCRIPTION?, DEFINITIONS?, INFO*, RESOURCE*)>
<!ATTLIST VOTABLE
        ID ID #IMPLIED
        version CDATA #IMPLIED
>

<!-- RESOURCEs can contain other RESOURCES,
     together with TABLEs and other stuff -->
<!ELEMENT RESOURCE (DESCRIPTION?, (INFO|PARAM|COOSYS)*, LINK*, TABLE*, RESOURCE*)>
<!ATTLIST RESOURCE
        name CDATA #IMPLIED
        ID ID #IMPLIED
        type (results | meta) "results"
>

<!ELEMENT DESCRIPTION (#PCDATA)>
<!ELEMENT DEFINITIONS (COOSYS|PARAM)*>

<!-- INFO is a name-value pair -->
<!ELEMENT INFO (#PCDATA)>
<!ATTLIST INFO
        ID ID #IMPLIED
        name CDATA #IMPLIED
        value CDATA #IMPLIED
>

<!-- A PARAM is similar to a FIELD, but it also has a "value attribute -->
<!ELEMENT PARAM (DESCRIPTION?, VALUES?, LINK*)>
<!ATTLIST PARAM
        ID   ID    #IMPLIED
        unit CDATA #IMPLIED
        datatype (boolean | bit | unsignedByte | short | int | long | char
        | unicodeChar | float | double | floatComplex | doubleComplex) #REQUIRED
        precision CDATA #IMPLIED
        width CDATA #IMPLIED
        ref   IDREF #IMPLIED
        name  CDATA #IMPLIED
        ucd   CDATA #IMPLIED
	utype CDATA #IMPLIED
        value CDATA #REQUIRED
        arraysize CDATA #IMPLIED
>

<!-- A PARAMref is a reference to a PARAM -->
<!ELEMENT PARAMref EMPTY>
<!ATTLIST PARAMref
	ref   IDREF  #REQUIRED
>

<!-- A TABLE is a sequence of FIELDS and LINKS and DESCRIPTION,
     possibly followed by a DATA section -->
<!-- ELEMENT TABLE (DESCRIPTION?, LINK*, FIELD*, DATA?) -->
<!ELEMENT TABLE (DESCRIPTION?, (FIELD|GROUP|PARAM)*, LINK*, DATA?)>
<!ATTLIST TABLE
        ID ID #IMPLIED
        name CDATA #IMPLIED
        ref IDREF #IMPLIED
        nrows CDATA #IMPLIED
>

<!-- GROUP can contain a description, fields/parameters and sub-groups -->
<!ELEMENT GROUP (DESCRIPTION?, (FIELD+|PARAM|GROUP|FIELDref|PARAMref)*)>
<!ATTLIST GROUP
	ID    ID    #IMPLIED
	name  CDATA #IMPLIED
	ref   IDREF #IMPLIED
	ucd   CDATA #IMPLIED
	utype CDATA #IMPLIED
>

<!-- FIELD is the definition of what is in a column of the table -->
<!-- ELEMENT FIELD (DESCRIPTION?, VALUES?, LINK?)* -->
<!ELEMENT FIELD (DESCRIPTION?, VALUES*, LINK*)>
<!ATTLIST FIELD
        ID   ID    #IMPLIED
        unit CDATA #IMPLIED
        datatype (boolean | bit | unsignedByte | short | int | long | char
        | unicodeChar | float | double | floatComplex | doubleComplex) #REQUIRED
        precision CDATA #IMPLIED
        width CDATA #IMPLIED
        ref   IDREF #IMPLIED
        name  CDATA #IMPLIED
        ucd   CDATA #IMPLIED
	utype CDATA #IMPLIED
        arraysize CDATA #IMPLIED
        type  (hidden | no_query | trigger) #IMPLIED
>

<!-- A FIELDref is a reference to a FIELD -->
<!ELEMENT FIELDref EMPTY>
<!ATTLIST FIELDref
	ref   IDREF  #REQUIRED
>

<!-- VALUES expresses the values that can be taken by the data in a column. -->
<!ELEMENT VALUES (MIN?, MAX?, OPTION*)>
<!ATTLIST VALUES
        ID   ID    #IMPLIED
        multiple (yes | no) "no"
        type (legal | actual) "legal"
        null CDATA #IMPLIED
        invalid CDATA #IMPLIED
>
<!ELEMENT MIN (#PCDATA)>
<!ATTLIST MIN
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT MAX (#PCDATA)>
<!ATTLIST MAX
        value CDATA #REQUIRED
        inclusive (yes | no) "yes"
>
<!ELEMENT OPTION (OPTION*)>
<!ATTLIST OPTION
        name CDATA #IMPLIED
        value CDATA #REQUIRED
>

<!-- The link is a URL (href) or some other kind of reference (gref). -->
<!ELEMENT LINK (#PCDATA)>
<!ATTLIST LINK
        ID ID #IMPLIED
        content-role (query | hints | doc) #IMPLIED
        content-type CDATA #IMPLIED
        title CDATA #IMPLIED
        value CDATA #IMPLIED
        href CDATA #IMPLIED
        gref CDATA #IMPLIED
        action CDATA #IMPLIED
>

<!-- DATA is the actual table data, in one of three formats -->
<!ELEMENT DATA (TABLEDATA | BINARY | FITS)>

<!-- Pure XML data -->
<!ELEMENT TABLEDATA (TR*)>
<!ELEMENT TR (TD+)>
<!ELEMENT TD (#PCDATA)>
<!ATTLIST TD
        ref IDREF #IMPLIED
>

<!-- FITS file, perhaps with specification of which extension to seek to -->
<!ELEMENT FITS (STREAM)>
<!ATTLIST FITS
        extnum CDATA #IMPLIED
>

<!-- Binary data format -->
<!ELEMENT BINARY (STREAM)>

<!-- Stream can be lcoal or remote, encoded or not -->
<!ELEMENT STREAM (#PCDATA)>
<!ATTLIST STREAM
        type (locator | other) "locator"
        href CDATA #IMPLIED
        actuate (onLoad | onRequest | other | none) "onRequest"
        encoding (gzip | base64 | dynamic | none) "none"
        expires CDATA #IMPLIED
        rights CDATA #IMPLIED
>

<!-- Expresses the coordinate system we are using -->
<!ELEMENT COOSYS (#PCDATA)>
<!ATTLIST COOSYS
        ID ID #IMPLIED
        equinox CDATA #IMPLIED
        epoch CDATA #IMPLIED
        system (eq_FK4 | eq_FK5 | ICRS | ecl_FK4 | ecl_FK5 | galactic
               | supergalactic | xy | barycentric | geo_app) "eq_FK5"
>

=== Starlink/starjava/ttools/src/testcases/uk/ac/starlink/ttools/task/heteroVOTable.xml
<?xml version="1.0"?>
<!DOCTYPE VOTABLE SYSTEM "http://us-vo.org/xml/VOTable.dtd">
<VOTABLE version="1.3">
<DESCRIPTION>Sample VOTable that tries to exercize the options</DESCRIPTION>
<RESOURCE>
<TABLE>

<FIELD ID="booleanFix" datatype="boolean" arraysize="2x2"/>
<FIELD ID="booleanVar" datatype="boolean" arraysize="*"/>

<FIELD ID="bitFix" datatype="bit" arraysize="2x2"/>
<FIELD ID="bitVar" datatype="bit" arraysize="*"/>

<FIELD ID="unsignedByteFix" datatype="unsignedByte" arraysize="2x2"/>
<FIELD ID="unsignedByteVar" datatype="unsignedByte" arraysize="*"/>

<FIELD ID="shortFix" datatype="short" arraysize="2x2"/>
<FIELD ID="shortVar" datatype="short" arraysize="*"/>

<FIELD ID="intFix" datatype="int" arraysize="2x2"/>
<FIELD ID="intVar" datatype="int" arraysize="*"/>

<FIELD ID="longFix" datatype="long" arraysize="2x2"/>
<FIELD ID="longVar" datatype="long" arraysize="*"/>

<FIELD ID="charFix" datatype="char" arraysize="2x2"/>
<FIELD ID="charVar" datatype="char" arraysize="*"/>

<FIELD ID="unicodeCharFix" datatype="unicodeChar" arraysize="2x2"/>
<FIELD ID="unicodeCharVar" datatype="unicodeChar" arraysize="*"/>

<FIELD ID="floatFix" datatype="float" arraysize="2x2"/>
<FIELD ID="floatVar" datatype="float" arraysize="*"/>

<FIELD ID="doubleFix" datatype="double" arraysize="2x2"/>
<FIELD ID="doubleVar" datatype="double" arraysize="*"/>

<FIELD ID="floatComplexFix" datatype="floatComplex" arraysize="2x2"/>
<FIELD ID="floatComplexVar" datatype="floatComplex" arraysize="*"/>

<FIELD ID="doubleComplexFix" datatype="doubleComplex" arraysize="2x2"/>
<FIELD ID="doubleComplexVar" datatype="doubleComplex" arraysize="*"/>


<DATA>
<TABLEDATA>

<TR>
<TD>T f T F</TD> <TD>T T t F f f</TD>
<TD>0 1 0 1</TD> <TD>1 0 1 0 1 0</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15</TD>
<TD>ABCD</TD> <TD>ABCDEF</TD>
<TD>ABCD</TD> <TD>ABCDEF</TD>
<TD>1.1 10.2 20.3 40.4</TD> <TD>1.1 3.2 5.3 7.4 9.5 11.6</TD>
<TD>1.1 10.2 20.3 40.4</TD> <TD>1.1 3.2 5.3 7.4 9.5 11.6</TD>
<TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0</TD> <TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0 1.5 9.0 1.6 9.0</TD>
<TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0</TD> <TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0 1.5 9.0 1.6 9.0</TD>
</TR>

<TR>
<TD>T f T F</TD> <TD>T T t F f f T 0 1 0 1 T F t t F</TD>
<TD>0 1 0 1</TD> <TD>1 0 1 0 1 0 1 0 1 0 1 0</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15 16 17 18 19</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15 16 17 18 19</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15 16 17 18 19</TD>
<TD>10 11 12 13</TD> <TD>10 11 12 13 14 15 16 17 18 19</TD>
<TD>ABCD</TD> <TD>ABCDEFGHIJK</TD>
<TD>ABCD</TD> <TD>ABCDEFGHIJK</TD>
<TD>1.1 1.2 1.3 1.4</TD> <TD>1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9</TD>
<TD>1.1 1.2 1.3 1.4</TD> <TD>1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9</TD>
<TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0</TD> <TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0 1.5 9.0 1.6 9.0 1.7 9.0 1.8 9.0 1.9 9.0</TD>
<TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0</TD> <TD>1.1 9.0 1.2 9.0 1.3 9.0 1.4 9.0 1.5 9.0 1.6 9.0 1.7 9.0 1.8 9.0 1.9 9.0</TD>
</TR>

</TABLEDATA>
</DATA>
</TABLE>
</RESOURCE>
</VOTABLE>
